<?php
/**
 * includes/defaults.php
 * القيم الافتراضية: فئات، أقسام فرعية، إعدادات، منتجات
 */
declare(strict_types=1);

function getDefaultDB(): array {
    return [
        'products'      => getDefaultProducts(),
        'settings'      => getDefaultSettings(),
        'subcategories' => getDefaultSubcategories(),
        'categories'    => getDefaultCategories(),
        'orders'        => [],
    ];
}

/**
 * منتجات بذرة — تُعرض عند عدم وجود MySQL، وبعد «إعادة ضبط المنتجات»،
 * وتُدمَج تلقائياً عندما تكون قائمة المنتجات في التخزين فارغة تماماً (أول تشغيل).
 *
 * السعر 1 د.ع placeholder كما طلب المستخدم — يُحدَّث لاحقاً من لوحة التحكم.
 *
 * @return list<array<string,mixed>>
 */
function getDefaultProducts(): array
{
    $now = date('Y-m-d H:i:s');

    return [
        [
            'id'                    => 'seed_panadol_extra_24',
            'name'                  => 'بنادول إكسترا — 24 قرص',
            'slug'                  => 'panadol-extra-24-tablets',
            'price'                 => 1,
            'stock'                 => 24,
            'badge'                 => '',
            'desc'                  => 'بنادول إكسترا أقراص فموية من GSK لتخفيف الألم الشديد والحمى، مع تركيبة تُساعِد الفعالية مقارنةً بالباراسيتامول وحده وفق التعليمات. العبوة 24 قرصاً. المعلومات للتوعية ولا تغني عن استشارة الصيدلي أو الطبيب.',
            'usage'                 => 'تخفيف الصداع، آلام العضلات والمفاصل، آلام الدورة الشهرية، ألم الأسنان، التهاب الحلق، والحمى المصاحبة للزكام والإنفلونزا عند البالغين حسب التعليمات.',
            'dose'                  => 'قرص واحد عند الحاجة؛ لا تتجاوز الجرعة القصوى اليومية الموضحة في النشرة.',
            'frequency'             => 'يُفضّل ترك 4–6 ساعات على الأقل بين الجرعات (حسب عمر المريض والنشرة).',
            'age'                   => 'عادة من 12 سنة فأكثر — راجع النشرة أو الصيدلي.',
            'storage'               => 'يُحفظ في مكان بارد وجاف بعيداً عن متناول الأطفال والضوء المباشر.',
            'warnings'              => 'يحتوي على باراسيتامول: تجنّب الجمع مع أدوية أخرى تحتوي باراسيتامولاً. احترس من جرعات زائدة خاصة مع أمراض الكبد أو شرب الكحول المزمن. يحتوي على كافيين: قد يسبب أرقاً أو عصبية عند الحساسية. لا تُستخدم أثناء الحمل أو الرضاعة دون استشارة طبية.',
            'ingredients'           => 'باراسيتامول 500 مجم + كافيين 65 مجم لكل قرص (تركيبة شائعة لبنادول إكسترا — راجع عبوة الدفعة لديك).',
            'contraindications'     => 'فرط الحساسية لمكونات المنتج. مرض كبدي شديد دون إشراف طبي. تجنّب الاستعمال دون استشارة عند بعض حالات القلب أو ارتفاع ضغط الدم غير المضبوط إن وُجدت موانع في النشرة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [1],
            'image'                 => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
            'images'                => ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80'],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_zecuf_100ml',
            'name'                  => 'زيكوف — شراب عشبي للسعال ١٠٠ مل',
            'slug'                  => 'zecuf-herbal-cough-syrup-100ml',
            'price'                 => 1,
            'stock'                 => 50,
            'badge'                 => '',
            'desc'                  => 'زيكوف (ZECUF) شراب عشبي للسعال، حجم ١٠٠ مل. المعلومات للتوعية فقط؛ راجع النشرة داخل العبوة للجرعة والمكونات والتحذيرات.',
            'usage'                 => 'مساعد لعلاج السعال وفق التعليمات الطبية أو نشرة المنتج.',
            'dose'                  => 'حسب العمر والجرعة الموضحة في النشرة المصاحبة للعبوة.',
            'frequency'             => 'حسب إرشادات الطبيب أو الصيدلي أو النشرة.',
            'age'                   => 'يُحدَّد حسب النشرة والفئة العمرية المذكورة.',
            'storage'               => 'يُحفظ حسب تعليمات النشرة؛ عادة في مكان بارد وجاف بعيداً عن متناول الأطفال.',
            'warnings'              => 'لا تتجاوز الجرعة المقررة. استشر الطبيب عند استمرار السعال أو ظهور أعراض خطيرة. راجع النشرة للموانع والتداخلات.',
            'ingredients'           => 'تركيبة عشبية للسعال — راجع الملصق أو النشرة للمكونات والتراكيز الدقيقة.',
            'contraindications'     => 'فرط الحساسية لمكونات المنتج. راجع النشرة للحالات الخاصة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3],
            'image'                 => '/assets/img/products/zecuf-100ml.png',
            'images'                => ['/assets/img/products/zecuf-100ml.png'],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_nunu_baby_powder_200g',
            'name'                  => 'نونو — بودرة أطفال (talc) ٢٠٠ غ',
            'slug'                  => 'nunu-baby-powder-talc-200g',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'بودرة أطفال نونو (Nunu) — talc، حجم ٢٠٠ غ. ملصق العبوة: «SOFTNESS CLINICALLY PROVEN»، «More Super Absorbent». معلومات للتوعية؛ راجع النشرة والتحذيرات على العبوة.',
            'usage'                 => 'للاستعمال الخارجي وفق تعليمات النشرة؛ تجنّب الاستنشاق المباشر وإبعادها عن وجه الطفل.',
            'dose'                  => 'رشّ كمية مناسبة حسب الحاجة بعد تنظيف وجفاف الجلد — حسب النشرة.',
            'frequency'             => 'عند الحاجة أو حسب إرشادات الطبيب/الصيدلي.',
            'age'                   => 'منتجات الأطفال — راجع النشرة للعمر المناسب.',
            'storage'               => 'يُحفظ في مكان جاف بارد بعيداً عن متناول الأطفال والحرارة والرطوبة.',
            'warnings'              => 'لا تُستخدم على جروح مفتوحة أو التهاب شديد دون استشارة. تجنّب ملامسة العينين. توقف الاستعمال عند ظهور تهيّج. بودرة التلك: اتبع تحذيرات النشرة المحلية.',
            'ingredients'           => 'talc — راجع الملصق للمكوّنات الكاملة.',
            'contraindications'     => 'فرط الحساسية لمكونات المنتج. راجع الطبيب عند الشك.',
            'product_type'          => 'cosmetic',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['kids'],
            'cat'                   => 'kids',
            'category'              => 'kids',
            'subcategories'         => [123],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_head_shoulders_charcoal_detox_shampoo',
            'name'                  => 'هيد آند شولدرز — شامبو ضد القشرة (ديتوكس الفحم بالأكسجين)',
            'slug'                  => 'head-shoulders-charcoal-oxygen-detox-anti-dandruff-shampoo',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Head & Shoulders — Oxygenated Charcoal Detox Anti-Dandruff Shampoo. شامبو ضد القشرة بفحم منشّط وأكسجين لتنظيف عميق للمسام وفروة رأس «تتنفس». مثبت مختبرياً — 100% بدون قشرة (حسب ادعاء العلامة على التغليف). معلومات للتوعية؛ راجع النشرة داخل العبوة.',
            'usage'                 => 'يُطبَّق على فروة الرأس والشعر، يُدلَّك بلطف ثم يُشطف — حسب تعليمات النشرة.',
            'dose'                  => 'كمية مناسبة لطول الشعر؛ كرّر الاستعمال حسب الحاجة أو النشرة.',
            'frequency'             => 'عند الغسيل أو حسب إرشادات الصيدلي.',
            'age'                   => 'للبالغين والأطفال حسب النشرة.',
            'storage'               => 'يُحفظ في مكان بارد وجاف بعيداً عن أشعة الشمس المباشرة.',
            'warnings'              => 'تجنّب ملامسة العينين. في حالة التهاب شديد أو جروح في فروة الرأس استشر الطبيب. توقف عند تهيّج شديد.',
            'ingredients'           => 'راجع الملصق للمكوّنات الكاملة (يشمل عادة عوامل تنظيف وفحم منشّط ومواد مضادة للقشرة حسب الترخيص).',
            'contraindications'     => 'فرط الحساسية لمكونات المنتج.',
            'product_type'          => 'cosmetic',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_pharmaline_ketonaz_shampoo',
            'name'                  => 'فارمالاين — كيتوناز شامبو (كيتوكونازول ٢٪)',
            'slug'                  => 'pharmaline-ketonaz-ketoconazole-2-shampoo',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'PHARMALINE — Ketonaz. شامبو مع Vitaliser، يحتوي على كيتوكونازول ٢٪. مضاد فطري (Antifungal) ومضاد قشرة (Antidandruff). معلومات للتوعية فقط؛ راجع النشرة الطبية والتحذيرات على العبوة.',
            'usage'                 => 'يُستخدم على فروة الرأس والشعر حسب تعليمات الطبيب أو الصيدلي أو النشرة المصاحبة.',
            'dose'                  => 'كمية مناسبة تُدلَّك بها فروة الرأس ثم تُشطف — حسب النشرة والمدة الموصى بها.',
            'frequency'             => 'حسب الوصفة أو النشرة (قد يكون مرتين أسبوعياً أو حسب الحالة).',
            'age'                   => 'للبالغين والأطفال حسب النشرة والاستطباب.',
            'storage'               => 'يُحفظ حسب تعليمات النشرة؛ عادة بعيداً عن الحرارة والرطوبة ومتناول الأطفال.',
            'warnings'              => 'كيتوكونازول: قد يسبب تهيّجاً موضعياً. تجنّب ملامسة العينين والأغشية المخاطية. استشر الطبيب عند الحمل أو الرضاعة أو إذا كانت فروة الرأس مصابة بجروح حادة. توقف عند فرط الحساسية.',
            'ingredients'           => 'المادة الفعالة: Ketoconazole ٢٪ — راجع الملصق للمكوّنات الكاملة والشكل الصيدلاني.',
            'contraindications'     => 'فرط الحساسية للكيتوكوناز أو لأي مكوّن في التركيبة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_alfacort_hydrocortisone_1_ointment_15g',
            'name'                  => 'ألفاكورت — مرهم (هيدروكورتيزون ١٪) ١٥ غ — Julphar',
            'slug'                  => 'alfacort-hydrocortisone-1-ointment-15g-julphar',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Alfacort — Hydrocortisone 1% w/w Ointment. مرهم يحتوي على هيدروكورتيزون ١٪ من شركة Julphar، وزن صافي ١٥ غ. للاستخدام الموضعي حسب الاستطباب (مثل بعض حالات الجلد والالتهاب الخفيف) — للتوعية فقط؛ راجع النشرة والوصفة.',
            'usage'                 => 'يُطبَّق طبقة رقيقة على المنطقة المصابة من الجلد حسب تعليمات الطبيب أو الصيدلي أو النشرة.',
            'dose'                  => 'كمية مناسبة تغطي المنطقة — التكرار والمدة حسب النشرة.',
            'frequency'             => 'عادة ١–٣ مرات يومياً أو حسب الوصفة؛ لا تُستخدم لفترة طويلة دون إشراف طبي.',
            'age'                   => 'للبالغين والأطفال حسب النشرة والعمر.',
            'storage'               => 'يُحفظ في مكان جاف بارد بعيداً عن الحرارة المباشرة ومتناول الأطفال.',
            'warnings'              => 'الكورتيزون الموضعي: قد يسبب ترقق الجلد أو تهيّجاً عند الاستعمال المطوّل أو على مساحات واسعة. تجنّب العينين والفم والأغشية المخاطية. استشر الطبيب عند الحمل أو الرضاعة أو عدوى جلدية غير مُعالَجة.',
            'ingredients'           => 'المادة الفعالة: Hydrocortisone 1% w/w — راجع الملصق للأساس والمواد المساعدة.',
            'contraindications'     => 'فرط الحساسية للهيدروكورتيزون أو لمكوّنات المرهم. موانع أخرى حسب النشرة (عدوى فيروسية جلدية معيّنة، إلخ).',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [14],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_alpecin_hybrid_sensitive_caffeine_shampoo',
            'name'                  => 'ألبيسين — Hybrid Sensitive شامبو كافيين (فروة حساسة وجافة)',
            'slug'                  => 'alpecin-hybrid-sensitive-caffeine-shampoo-dr-wolff',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Alpecin Hybrid Sensitive Caffeine Shampoo — DR. WOLFF، صناعة ألمانيا. للفروة الحساسة والجافة؛ يُقلّل الحكة ويُساعد على تقليل التساقط (حسب ادعاء العلامة). معلومات للتوعية؛ راجع النشرة.',
            'usage'                 => 'يُطبَّق على فروة الرأس والشعر، يُدلَّك ثم يُشطف — حسب النشرة.',
            'dose'                  => 'كمية مناسبة لطول الشعر.',
            'frequency'             => 'عند الغسيل أو حسب إرشاد الصيدلي.',
            'age'                   => 'للبالغين حسب النشرة.',
            'storage'               => 'يُحفظ بعيداً عن الحرارة والرطوبة.',
            'warnings'              => 'تجنّب ملامسة العينين. توقف عند تهيّج شديد.',
            'ingredients'           => 'شامبو كافيين — راجع الملصق للمكوّنات.',
            'contraindications'     => 'فرط الحساسية لمكوّنات المنتج.',
            'product_type'          => 'cosmetic',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_stoplice_lice_nits_shampoo_250ml',
            'name'                  => 'ستوبلايس — شامبو القمل والصئبان ٢٥٠ مل (koniCARE)',
            'slug'                  => 'stoplice-lice-nits-shampoo-250ml-konicare',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'STOPLICE Lice–Nits Shampoo — koniCARE، ٢٥٠ مل. يُرفق مشط خاص (حسب التغليف). رجّح العبوة جيداً قبل الاستعمال. للتوعية؛ اتبع النشرة وإرشاد الصيدلي لعلاج القمل.',
            'usage'                 => 'حسب النشرة الطبية — عادة على الشعر الجاف أو الرطب كما يُنصح؛ يُشطف جيداً.',
            'dose'                  => 'كمية تغطي الشعر بالكامل — حسب العمر والنشرة.',
            'frequency'             => 'قد يتكرر حسب البرنامج العلاجي؛ راجع النشرة.',
            'age'                   => 'للأطفال والبالغين حسب النشرة.',
            'storage'               => 'يُحفظ بعيداً عن متناول الأطفال.',
            'warnings'              => 'للاستعمال الخارجي على الشعر والفروة فقط. تجنّب العينين. لا تُبلع.',
            'ingredients'           => 'راجع الملصق للمواد الفعالة والمساعدة.',
            'contraindications'     => 'فرط الحساسية لمكوّنات الشامبو.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_arak_minoxidil_vitamin_b5_shampoo_dry',
            'name'                  => 'أراك — شامبو مينوكسيديل + فيتامين ب٥ (للشعر الجاف)',
            'slug'                  => 'arak-minoxidil-vitamin-b5-shampoo-dry-hair',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Minoxidil Vitamin B5 Shampoo — للشعر الجاف. صياغة علمية لتقوية الشعر الرقيق؛ يزيل الزيت الزائد؛ يقلل التساقط؛ يدعم النمو؛ يؤخر ظهور الشيب (حسب ادعاء التغليف). إنتاج U.A.E. لصالح AL ANAS — حلب سوريا (حسب المعلومات على العبوة). للتوعية فقط.',
            'usage'                 => 'يُطبَّق على الشعر والفروة، يُدلَّك ثم يُشطف — حسب النشرة.',
            'dose'                  => 'كمية مناسبة.',
            'frequency'             => 'حسب النشرة أو الصيدلي.',
            'age'                   => 'للبالغين عادةً — راجع النشرة.',
            'storage'               => 'يُحفظ في مكان جاف.',
            'warnings'              => 'تجنّب ملامسة العينين. استشر الطبيب عند الحمل أو أمراض فروة الرأس.',
            'ingredients'           => 'راجع الملصق (مينوكسيديل، فيتامين ب٥، وغيرها).',
            'contraindications'     => 'فرط الحساسية لمكوّنات المنتج.',
            'product_type'          => 'cosmetic',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_arak_minoxidil_shampoo_normal',
            'name'                  => 'أراك — شامبو مينوكسيديل (للشعر العادي)',
            'slug'                  => 'arak-minoxidil-shampoo-normal-hair',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Minoxidil Shampoo — للشعر العادي/الرقيق. يزيل الزيت الزائد؛ يقلل التساقط؛ يدعم النمو (حسب ادعاء التغليف). إنتاج U.A.E. لصالح AL ANAS — حلب سوريا. للتوعية فقط.',
            'usage'                 => 'يُطبَّق ويُدلَّك ثم يُشطف — حسب النشرة.',
            'dose'                  => 'كمية مناسبة لطول الشعر.',
            'frequency'             => 'حسب النشرة.',
            'age'                   => 'للبالغين حسب النشرة.',
            'storage'               => 'يُحفظ في مكان جاف.',
            'warnings'              => 'تجنّب العينين. استشر الطبيب عند الحمل أو القلق من تساقط الشعر المرضي.',
            'ingredients'           => 'راجع الملصق.',
            'contraindications'     => 'فرط الحساسية لمكوّنات المنتج.',
            'product_type'          => 'cosmetic',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_omega_pharma_lavender_shampoo_almond_castor',
            'name'                  => 'أوميغا فارما — شامبو لافندر + زيت لوز وخروع (شعر خشن وأجعد)',
            'slug'                  => 'omega-pharma-lavender-shampoo-almond-castor-coarse-curly',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Omega Pharma — شامبو لافندر يمنع تساقط الشعر، مع فيتامين ب٥ ونانوكسيديل؛ زيت اللوز والخروع — للشعر الخشن والأجعد؛ شعر حريري ومتألق (حسب التغليف). للتوعية فقط.',
            'usage'                 => 'يُطبَّق على الشعر الرطب، يُدلَّك ثم يُشطف.',
            'dose'                  => 'كمية مناسبة.',
            'frequency'             => 'عند الغسيل.',
            'age'                   => 'حسب النشرة.',
            'storage'               => 'يُحفظ في مكان جاف.',
            'warnings'              => 'تجنّب العينين.',
            'ingredients'           => 'راجع الملصق (لافندر، فيتامين ب٥، نانوكسيديل، زيوت).',
            'contraindications'     => 'فرط الحساسية لمكوّنات المنتج.',
            'product_type'          => 'cosmetic',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_omega_pharma_lavender_shampoo_egg_protein',
            'name'                  => 'أوميغا فارما — شامبو لافندر + بروتين البيض (شعر ضعيف ومرهق)',
            'slug'                  => 'omega-pharma-lavender-shampoo-egg-protein-weak-hair',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Omega Pharma — شامبو لافندر مغذٍ للشعر؛ يمنع التساقط؛ مع فيتامين ب٥ ونانوكسيديل؛ بروتين البيض — للشعر الضعيف والمرهق (حسب التغليف). للتوعية فقط.',
            'usage'                 => 'يُطبَّق ويُدلَّك ثم يُشطف — حسب النشرة.',
            'dose'                  => 'كمية مناسبة.',
            'frequency'             => 'عند الغسيل.',
            'age'                   => 'حسب النشرة.',
            'storage'               => 'يُحفظ في مكان جاف.',
            'warnings'              => 'تجنّب العينين.',
            'ingredients'           => 'راجع الملصق.',
            'contraindications'     => 'فرط الحساسية لمكوّنات المنتج.',
            'product_type'          => 'cosmetic',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['haircare'],
            'cat'                   => 'haircare',
            'category'              => 'haircare',
            'subcategories'         => [141],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_fusidad_fusidic_acid_2_cream_15g',
            'name'                  => 'فيوسيداد — كريم جلدي (حمض الفيوسيديك ٢٪) ١٥ غ — WPC',
            'slug'                  => 'fusidad-fusidic-acid-2-cream-15g-wadi-alrafidain',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'فيوسيداد — كريم جلدي، المادة الفعالة حمض الفيوسيديك ٢٪، وزن ١٥ غم. للاستعمال الخارجي فقط — WPC وادي الرافدين. مضاد حيوي موضعي للعدوى الجرثومية السطحية حسب الاستطباب؛ للتوعية فقط؛ راجع النشرة والوصفة.',
            'usage'                 => 'طبقة رقيقة على الجلد النظيف حسب تعليمات الطبيب أو النشرة.',
            'dose'                  => 'كمية تغطي المنطقة — التكرار حسب النشرة.',
            'frequency'             => 'عادة ٣–٤ مرات يومياً أو حسب الوصفة.',
            'age'                   => 'حسب النشرة والعمر.',
            'storage'               => 'يُحفظ بعيداً عن الحرارة ومتناول الأطفال.',
            'warnings'              => 'قد يسبب تهيّجاً موضعياً. لا يُستخدم طويلاً دون إشراف طبي. تجنّب العينين والفم.',
            'ingredients'           => 'Fusidic acid 2% — راجع الملصق للأساس الكامل.',
            'contraindications'     => 'فرط الحساسية للفيوسيديك أو للقاعدة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [14],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_isilin_syrup_120ml_elnile',
            'name'                  => 'إيسيلين (Isilin) — شراب ١٢٠ مل — طارد بلغم ومضاد هيستامين — النيل مصر',
            'slug'                  => 'isilin-expectorant-antihistaminic-syrup-120ml-el-nile-egypt',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Isilin — شراب فموي ١٢٠ مل، مذكور على التغليف كـ Expectorant & Antihistaminic (طارد للبلغم ومضاد للهيستامين). من إنتاج شركة النيل للأدوية والصناعات الكيماوية (El-NILE Co. For Pharmaceuticals And Chemical Industries) — القاهرة، جمهورية مصر العربية. رقم تسجيل ظاهر على العبوة: R.C.C. 115668. المعلومات للتوعية فقط ولا تغني عن النشرة الطبية أو استشارة الصيدلي/الطبيب.',
            'usage'                 => 'يُستخدم فموياً حسب الاستطباب لدعم طرد البلغم وللأعراض المرتبطة بالحساسية وفق النشرة المصاحبة للعبوة أو حسب وصفة الطبيب.',
            'dose'                  => 'الجرعة والمدة حسب العمر والوزن والنشرة داخل العبوة؛ لا تتجاوز الجرعة المقررة.',
            'frequency'             => 'عدد المرات اليومية حسب النشرة أو إرشادات الطبيب/الصيدلي.',
            'age'                   => 'يُحدَّد حسب النشرة والفئة العمرية المسموح بها للمنتج.',
            'storage'               => 'STORE AT ROOM TEMPERATURE — يُحفظ في مكان جاف عند درجة حرارة الغرفة بعيداً عن الرطوبة المباشرة ومتناول الأطفال والضوء الشديد.',
            'warnings'              => 'قد يسبب النعاساً أو دواراً عند بعض الأشخاص (مضادات هيستامين). تجنّب القيادة أو تشغيل الآلات إن ظهرت أعراض منومة. استشر الطبيب عند الحمل أو الرضاعة أو أمراض مزمنة أو مع أدوية أخرى. توقف الاستعمال واستشر الطبيب عند تفاقم السعال أو صعوبة التنفس أو حمى شديدة.',
            'ingredients'           => 'التركيبة الكاملة والمواد الفعالة والتراكيز — راجع نشرة المنتج وملصق الدفعة (الشركة: El-NILE).',
            'contraindications'     => 'فرط الحساسية لأي مكوّن في التركيبة. موانع أخرى حسب النشرة الرسمية.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3, 4],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_prospan_ivy_cough_syrup_100ml',
            'name'                  => 'بروسبان (Prospan) — شراب للسعال ١٠٠ مل — خلاصة أوراق اللبلاب',
            'slug'                  => 'prospan-ivy-leaf-dry-extract-cough-syrup-100ml',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Prospan — شراب للسعال، حجم ١٠٠ مل. المادة الفعالة شائعة التسمية على التغليف: خلاصة أوراق اللبلاب المجففة (Ivy leaves dry extract). يُذكر على العبوات عادةً أنه خالٍ من الكحول والسكر وخالٍ من ملونات صناعية، مع خصائص مذكورة للتسويق مثل: Secretolytic (إفرازي/مذيب)، Spasmolytic (مضاد تشنج قصبي)، ومساعد لتخفيف السعال — حسب ادعاء التغليف والنشرة. المعلومات للتوعية فقط؛ راجع النشرة الرسمية للدفعة لديك أو استشر الصيدلي/الطبيب.',
            'usage'                 => 'للسعال والبلغم وفق الاستطباب الموضح في النشرة المصاحبة للعبوة أو حسب وصفة الطبيب.',
            'dose'                  => 'الجرعة بالمللتر أو بالمِلعقة حسب العمر والوزن — تُحدَّد بدقة من النشرة داخل العبوة.',
            'frequency'             => 'عدد الجرعات اليومية والمدة حسب النشرة أو إرشادات الطبيب/الصيدلي.',
            'age'                   => 'يُحدَّد حسب النشرة (غالباً للأطفال والبالغين بجرعات مختلفة).',
            'storage'               => 'يُحفظ في مكان جاف بارد بعيداً عن أشعة الشمس المباشرة ومتناول الأطفال؛ راجع درجة الحرارة الموصى بها على النشرة.',
            'warnings'              => 'لا تتجاوز الجرعة أو المدة الموصى بها. استشر الطبيب عند سعال دام أكثر من أسبوع، أو حمى، أو دم مع البلغم، أو ضيق تنفس. راجع النشرة عند الحمل أو الرضاعة أو الأمراض المزمنة.',
            'ingredients'           => 'Ivy leaves dry extract (خلاصة أوراق اللبلاب المجففة) — راجع الملصق للتركيز لكل ١٠٠ مل والمواد المساعدة الكاملة.',
            'contraindications'     => 'فرط الحساسية لأي مكوّن في التركيبة. موانع أخرى حسب النشرة الرسمية.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_ankle_support_compression_no9175',
            'name'                  => 'دعامة كاحل — ANKLE SUPPORT — ضغط متعدد الاتجاهات — NO 9175',
            'slug'                  => 'ankle-support-compression-multi-directional-no9175',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'دعامة/كمادة كاحل من التغليف التسويقي «HIGH QUALITY ANKLE» — ANKLE SUPPORT. مذكور على العلبة: ضغط متعدد الاتجاهات (MULTI DIRECTIONAL COMPRESSION)، خياطة مسطّحة (FLATLOCK STITCHING)، وحواف معزّزة (DURABLE REINFORCED EDGING). رقم الطراز الظاهر: NO 9175. للاستعمال الخارجي الداعم للكاحل وفق التعليمات — للتوعية فقط.',
            'usage'                 => 'يُلبَس على الكاحل حسب مقاس العبوة والنشرة؛ لا تُشدّ بشكل يعيق الدورة الدموية.',
            'dose'                  => '—',
            'frequency'             => 'حسب الحاجة أو إرشادات الطبيب/الصيدلي.',
            'age'                   => 'للبالغين عادةً — راجع العبوة للفئة العمرية.',
            'storage'               => 'يُحفظ في مكان جاف بعيداً عن الحرارة المباشرة ومتناول الأطفال.',
            'warnings'              => 'توقف الاستعمال عند ألم شديد، تنميل مستمر، ازرقاق، أو تورم يزداد. استشر الطبيب بعد الإصابات الحادة أو الكسور.',
            'ingredients'           => 'مستلزم دعم وليس دواءً فموياً — المواد حسب الملصق (ألياف/مطاط/إلخ).',
            'contraindications'     => 'لا يُستخدم كبديل عن العلاج الطبي للكسور دون إشراف.',
            'product_type'          => 'device',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medical'],
            'cat'                   => 'medical',
            'category'              => 'medical',
            'subcategories'         => [115],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_mucosolf_bromhexine_strawberry_syrup_100ml',
            'name'                  => 'ميوكوسولف (Mucosolf) — شراب ١٠٠ مل — برومهيكسين هيدروكلورايد — فراولة — بايونير',
            'slug'                  => 'mucosolf-bromhexine-hcl-100ml-strawberry-syrup-pioneer',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'ميوكوسولف — شراب ١٠٠ مل بنكهة الفراولة. المادة الفعالة المذكورة على التغليف: برومهيكسين هيدروكلورايد (Bromhexine Hydrochloride). يُذكر للسعال المنتج والبلغم، مع إيحاء بذوبان البلغم وتخفيف احتقان القصبات، وخلوٍّ من الكحول والسكر، وأنه لا يسبب النعاس — حسب ادعاء العبوة. الشركة: Pioneer for Pharmaceutical Industries (بايونير للصناعات الدوائية). للتوعية فقط؛ راجع النشرة.',
            'usage'                 => 'فموياً للسعال المصحوب ببلغم وفق النشرة أو وصفة الطبيب.',
            'dose'                  => 'حسب العمر والوزن والنشرة بالمللتر أو الملعقة.',
            'frequency'             => 'عدد الجرعات اليومية حسب النشرة.',
            'age'                   => 'يُحدَّد حسب النشرة.',
            'storage'               => 'يُحفظ بعيداً عن الحرارة والرطوبة ومتناول الأطفال.',
            'warnings'              => 'لا تتجاوز الجرعة. استشر الطبيب عند سعال طويل أو حمى أو ضيق نفس. راجع التداخلات والحمل والرضاعة في النشرة.',
            'ingredients'           => 'Bromhexine HCl — راجع الملصق للتركيز والأساس.',
            'contraindications'     => 'فرط الحساسية للبرومهيكسين أو للمكوّنات. موانع أخرى حسب النشرة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3, 2],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_ivy_calm_cough_syrup_120ml',
            'name'                  => 'Ivy-Calm — شراب للسعال ١٢٠ مل — خلاصة أوراق اللبلاب الجافة',
            'slug'                  => 'ivy-calm-cough-syrup-120ml-ivy-leaf-dry-extract',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Ivy-Calm — شراب للسعال، حجم ١٢٠ مل. يُذكر على التغليف: خالٍ من الكحول والسكر وبدون ملونات؛ ختم IVY LEAF DRY EXTRACT؛ خصائص مذكورة مثل Secretolytic و Spasmolytic و Cough-relieving. المعلومات للتوعية فقط — راجع النشرة الرسمية.',
            'usage'                 => 'للسعال والجهاز التنفسي العلوي وفق النشرة أو إرشادات مختص.',
            'dose'                  => 'حسب العمر والنشرة.',
            'frequency'             => 'حسب النشرة.',
            'age'                   => 'حسب النشرة.',
            'storage'               => 'مكان جاف بارد بعيداً عن أشعة الشمس ومتناول الأطفال.',
            'warnings'              => 'لا تتجاوز الجرعة. استشر الطبيب عند تفاقم الأعراض.',
            'ingredients'           => 'Ivy leaf dry extract — راجع الملصق للتركيز والمواد المساعدة.',
            'contraindications'     => 'فرط الحساسية لمكوّنات التركيبة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_solan_children_cough_cold_strawberry_100ml',
            'name'                  => 'سولان (Solan) — شراب أطفال للسعال والزكام ١٠٠ مل — فراولة',
            'slug'                  => 'solan-children-cough-cold-strawberry-syrup-100ml',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'سولان — شراب للأطفال للسعال والزكام، حجم ١٠٠ مل، بنكهة الفراولة (حسب التغليف). معلومات للتوعية فقط؛ راجع النشرة للجرعة حسب العمر والموانع.',
            'usage'                 => 'فموياً حسب النشرة أو وصفة الطبيب.',
            'dose'                  => 'جرعة الأطفال تُحدَّد بدقة من النشرة حسب الوزن/العمر.',
            'frequency'             => 'حسب النشرة.',
            'age'                   => 'منتج موجّه للأطفال — راجع الفئة العمرية على العبوة.',
            'storage'               => 'يُحفظ بعيداً عن متناول الأطفال (إلا تحت إشراف) وبعيداً عن الحرارة.',
            'warnings'              => 'لا تُعطَ للرضع دون استشارة. راقب الأعراض؛ راجع الطبيب عند حمى عالية أو ضيق نفس.',
            'ingredients'           => 'راجع الملصق للمواد الفعالة والتراكيز.',
            'contraindications'     => 'فرط الحساسية لمكوّنات الشراب.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['kids'],
            'cat'                   => 'kids',
            'category'              => 'kids',
            'subcategories'         => [126, 3],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_bronquium_elixir_syrup_120ml_ferrer',
            'name'                  => 'Bronquium® ELIXIR — شراب ١٢٠ مل — فيرير (ferrer)',
            'slug'                  => 'bronquium-elixir-syrup-120ml-ferrer',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Bronquium® ELIXIR — شراب فموي، حجم ١٢٠ مل. على التغليف تظهر عبارات عربية مثل: عدم ترك الدواء في متناول الأطفال، والتخزين عند درجة حرارة أقل من ٣٠°م — راجع النشرة الكاملة. العلامة التجارية الظاهرة: ferrer. للتوعية فقط.',
            'usage'                 => 'حسب الاستطباب والنشرة أو وصفة الطبيب.',
            'dose'                  => 'حسب العمر والنشرة.',
            'frequency'             => 'حسب النشرة.',
            'age'                   => 'حسب النشرة.',
            'storage'               => 'أقل من ٣٠°م — بعيداً عن متناول الأطفال (كما على العبوة).',
            'warnings'              => 'راجع النشرة للتحذيرات والموانع والتداخلات.',
            'ingredients'           => 'راجع الملصق للمواد الفعالة.',
            'contraindications'     => 'حسب النشرة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3, 2],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_doppelherz_ribosan_cough_syrup_100ml',
            'name'                  => 'دوبل هيرتس aktiv — RIBOSAN شراب سعال ١٠٠ مل — مستخلص نبات السنط',
            'slug'                  => 'doppelherz-aktiv-ribosan-cough-syrup-100ml-ribwort',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Doppel herz aktiv — RIBOSAN Cough Syrup، ١٠٠ مل. يُذكر على التغليف: With Ribwort extract؛ تخفيف سريع للسعال الجاف وألم الحلق؛ تأثير مضاد بكتيري طبيعي (حسب ادعاء العلامة)؛ غير منوّم وخالٍ من الكحول؛ للعائلة — حسب النص التسويقي. المعلومات للتوعية فقط؛ راجع النشرة.',
            'usage'                 => 'فموياً حسب النشرة.',
            'dose'                  => 'حسب العمر والنشرة.',
            'frequency'             => 'حسب النشرة.',
            'age'                   => 'يُذكر «للعائلة» — راجع النشرة للأطفال.',
            'storage'               => 'يُحفظ حسب النشرة؛ جاف وبارد.',
            'warnings'              => 'استشر الطبيب عند أعراض شديدة أو طويلة.',
            'ingredients'           => 'Ribwort extract — راجع الملصق للتركيز والمواد الأخرى.',
            'contraindications'     => 'فرط الحساسية لمكوّنات التركيبة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3, 2],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_x_cough_dextromethorphan_orange_100ml_pioneer',
            'name'                  => 'X-COUGH — شراب سعال جاف ١٠٠ مل — ديكستروميثورفان — برتقال — بايونير',
            'slug'                  => 'x-cough-dextromethorphan-dry-cough-orange-100ml-pioneer',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'X-COUGH — شراب ١٠٠ مل بنكهة البرتقال. المادة الفعالة المذكورة على التغليف: Dextromethorphan HBr بتركيز ١٥ مجم / ٥ مل للسعال الجاف (Dry cough). يُذكر: مهدّئ، يخفف السعال المستمر، غير منوّم، خالٍ من الكحول — حسب العبوة. الشركة: PIONEER Co. for Pharmaceutical Industries. للتوعية فقط؛ راجع النشرة.',
            'usage'                 => 'للسعال الجاف وفق النشرة أو الوصفة.',
            'dose'                  => 'حسب العمر والوزن — تُستخرج بدقة من النشرة (مثال شائع على العبوات: ١٥ مجم ديكستروميثورفان لكل ٥ مل).',
            'frequency'             => 'حسب النشرة.',
            'age'                   => 'حسب النشرة.',
            'storage'               => 'بعيداً عن الحرارة والرطوبة ومتناول الأطفال.',
            'warnings'              => 'ديكستروميثورفان: تجنّب الجمع مع مثبطات أخرى للسعال أو أدوية قد تسبب النعاس دون إشراف. استشر الطبيب عند الربو أو الأدوية المزمنة.',
            'ingredients'           => 'Dextromethorphan Hydrobromide 15mg/5ml — راجع الملصق للأساس الكامل.',
            'contraindications'     => 'فرط الحساسية. موانع أخرى حسب النشرة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_lumbar_support_belt_gdd011_kangpai',
            'name'                  => 'حزام تثبيت فقرات قطنية — Lumbar Vertebra Fixing Belt — (GDD-011) — كانغباي',
            'slug'                  => 'lumbar-vertebra-fixing-belt-gdd011-hengshui-kangpai',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'حزام تثبيت للفقرات القطنية — Lumbar Vertebra Fixing Belt، الطراز (GDD-011). شعار التغليف: DL / 鼎力. الشركة الظاهرة: Hengshui Kangpai medical supplies Co., Ltd (衡水康派医疗用品有限公司). نطاق الاستعمال المذكور على العلبة (ترجمة تقريبية): دعم وتثبيت عند الحاجة — راجع النص الأصلي على المنتج. للاستعمال كمستلزم دعم وليس دواءً فموياً.',
            'usage'                 => 'يُلبَس حسب تعليمات العبوة؛ لا يُشدّ بإفراط.',
            'dose'                  => '—',
            'frequency'             => 'حسب الحاجة أو نصيحة مختص.',
            'age'                   => 'للبالغين عادةً — راجع العبوة.',
            'storage'               => 'جاف، بعيداً عن الرطوبة.',
            'warnings'              => 'استشر الطبيب عند آلام شديدة، خدر، أو أعراض عصبية. لا يُعد بديلاً عن العلاج الطبي للكسور.',
            'ingredients'           => 'مستلزم طبي — مواد التصنيع حسب الملصق.',
            'contraindications'     => 'لا يُستخدم دون تشخيص عند الإصابات الحادة دون إشراف.',
            'product_type'          => 'device',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medical'],
            'cat'                   => 'medical',
            'category'              => 'medical',
            'subcategories'         => [115],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_decopect_antitussive_syrup_100ml_pioneer',
            'name'                  => 'ديكوبكت (Decopect) — شراب مضاد للسعال ١٠٠ مل — بايونير',
            'slug'                  => 'decopect-antitussive-syrup-100ml-pioneer',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Decopect / ديكوبكت — شراب ١٠٠ مل، مذكور كـ Antitussive (مضاد للسعال). المكونات المذكورة على التغليف شائعاً: Glyceryl Guaiacolate (غليسريل غواياكوليت)، Chlorpheniramine Maleate (كلورفينيرامين مالييت)، Phenylephrine HCl (فينيليفرين هيدروكلوريد) — راجع دفعة المنتج للتراكيز الدقيقة. الشركة: Pioneer (بايونير). للتوعية فقط؛ راجع النشرة.',
            'usage'                 => 'للسعال والأعراض المصاحبة وفق النشرة أو الوصفة.',
            'dose'                  => 'حسب العمر والوزن والنشرة.',
            'frequency'             => 'حسب النشرة.',
            'age'                   => 'حسب النشرة.',
            'storage'               => 'يُحفظ بعيداً عن الحرارة ومتناول الأطفال.',
            'warnings'              => 'يحتوي على مضاد هيستامين وفينيليفرين: راجع التداخلات وضغط الدم والغدة الدرقية والحمل في النشرة. لا تتجاوز الجرعة.',
            'ingredients'           => 'Guaifenesin-related: Glyceryl guaiacolate؛ Chlorpheniramine maleate؛ Phenylephrine HCl — راجع الملصق.',
            'contraindications'     => 'فرط الحساسية. موانع أخرى حسب النشرة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [3, 2],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_movineer_meloxicam_7_5mg_30_tablets_pioneer',
            'name'                  => 'موفينير (MOVINEER®) — ميلوكسيكام ٧٫٥ مجم — ٣٠ قرصاً — بايونير',
            'slug'                  => 'movineer-meloxicam-7-5mg-30-tablets-pioneer',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'MOVINEER® — أقراص تحتوي على المادة الفعالة ميلوكسيكام (Meloxicam) بقوة ٧٫٥ مجم، علبة ٣٠ قرصاً كما يظهر على التغليف. من إنتاج PIONEER Co. for Pharmaceutical Industries (بايونير للصناعات الدوائية). الميلوكسيكام من مضادات الالتهاب غير الستيرويدية (NSAID) شائعة الاستخدام في بعض حالات الألم والالتهاب حسب الاستطباب — للتوعية فقط؛ راجع النشرة والوصفة.',
            'usage'                 => 'فموياً حسب وصفة الطبيب أو النشرة؛ غالباً مع الطعام أو الحليب إن أوصت النشرة بذلك.',
            'dose'                  => '٧٫٥ مجم حسب تكرار النشرة — لا تغيّر الجرعة دون طبيب.',
            'frequency'             => 'حسب النشرة (مرة أو أكثر يومياً حسب الحالة).',
            'age'                   => 'للبالغين عادةً — موانع وجرعات أطفال حسب النشرة.',
            'storage'               => 'يُحفظ حسب تعليمات النشرة؛ عادة بارد وجاف بعيداً عن متناول الأطفال.',
            'warnings'              => 'NSAID: قد يسبب اضطراباً معدياً معوياً؛ احترس مع قرحة المعدة، الفشل الكلوي/الكبدي، أمراض القلب والأوعية، والحمل المتأخر. تجنّب الجمع مع أدوية NSAID أخرى. استشر الطبيب عند الحمل أو الرضاعة.',
            'ingredients'           => 'Meloxicam 7.5 mg per tablet — راجع الملصق للأساس والمواد المساعدة.',
            'contraindications'     => 'فرط الحساسية للميلوكسيكام أو لمضادات الالتهاب غير الستيرويدية. موانع أخرى حسب النشرة (قرحة نشطة، إلخ).',
            'product_type'          => 'medicine',
            'prescription_required' => true,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [1],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_adol_paracetamol_syrup_120mg_5ml_100ml_julphar',
            'name'                  => 'أدول شراب (Adol Syrup) — باراسيتامول ١٢٠ مجم/٥ مل — ١٠٠ مل — جلفار',
            'slug'                  => 'adol-paracetamol-syrup-120mg-per-5ml-100ml-julphar',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Adol Syrup / أدول شراب — حجم ١٠٠ مل. المادة الفعالة: باراسيتامول (Paracetamol) بتركيز ١٢٠ مجم لكل ٥ مل كما يظهر على التغليف. يُذكر خلوُّه من الكحول (Alcohol-Free). من شركة Julphar (جلفار). مسكن للألم وخافض للحرارة للاستعمال الفموي حسب النشرة — للتوعية فقط.',
            'usage'                 => 'فموياً للحمى والألم الخفيف إلى المتوسط حسب العمر والوزن والنشرة.',
            'dose'                  => 'يُقاس بالملعقة أو المِلّي وفق جدول الجرعات في النشرة.',
            'frequency'             => 'لا تتجاوز الجرعة اليومية القصوى؛ ترك فاصل بين الجرعات حسب النشرة.',
            'age'                   => 'غالباً للأطفال — راجع جدول العمر على النشرة.',
            'storage'               => 'يُحفظ بعيداً عن الحرارة ومتناول الأطفال.',
            'warnings'              => 'يحتوي على باراسيتامول: لا تجمع مع أدوية أخرى تحتويه. احترس من الجرعة الزائدة ومرض الكبد. استشر الطبيب عند الحمى الطويلة أو ألم شديد.',
            'ingredients'           => 'Paracetamol 120 mg / 5 mL — راجع الملصق للمواد المساعدة.',
            'contraindications'     => 'فرط الحساسية للباراسيتامول. موانع أخرى حسب النشرة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['kids', 'medicine'],
            'cat'                   => 'kids',
            'category'              => 'kids',
            'subcategories'         => [126, 1],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_arthri_flex_analgesic_cream_100g_adrien_gagnon',
            'name'                  => 'Arthri Flex — كريم مسكن ١٠٠ غ — من مكونات فعالة طبيعية — Adrien Gagnon',
            'slug'                  => 'arthri-flex-analgesic-cream-100g-adrien-gagnon',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Arthri Flex — Analgesic Cream، وزن ١٠٠ غ. يُذكر على التغليف: من مكونات فعالة طبيعية (from Natural Active Ingredients)، غير دهني (Non Greasy)، وتخفيف سريع لآلام العضلات والمفاصل/التهاب المفاصل (Fast-Acting Muscle and Arthritis Pain Relief) — حسب النص التسويقي. العلامة: ADRIEN GAGNON. للاستعمال الخارجي فقط؛ للتوعية فقط؛ راجع النشرة.',
            'usage'                 => 'يُدلَّك بلطف على المنطقة المصابة حسب النشرة.',
            'dose'                  => 'كمية كافية تغطي المنطقة — التكرار حسب النشرة.',
            'frequency'             => 'حسب الحاجة أو النشرة.',
            'age'                   => 'حسب النشرة.',
            'storage'               => 'يُحفظ في مكان جاف بارد.',
            'warnings'              => 'للاستعمال الخارجي فقط. تجنّب العينين والأغشية المخاطية والجروح المفتوحة. توقف عند تهيّج شديد.',
            'ingredients'           => 'راجع الملصق والنشرة العربية للمكوّنات الكاملة.',
            'contraindications'     => 'فرط الحساسية لمكوّنات الكريم.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['medicine'],
            'cat'                   => 'medicine',
            'category'              => 'medicine',
            'subcategories'         => [14],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
        [
            'id'                    => 'seed_adol_paracetamol_suppositories_125mg_10_julphar',
            'name'                  => 'أدول تحاميل (Adol) — باراسيتامول ١٢٥ مجم — ١٠ تحاميل — جلفار',
            'slug'                  => 'adol-paracetamol-125mg-10-suppositories-julphar',
            'price'                 => 1,
            'badge'                 => '',
            'desc'                  => 'Adol — تحاميل (Suppositories) تحتوي على باراسيتامول ١٢٥ مجم، عبوة ١٠ تحاميل كما على التغليف. مسكن للألم وخافض للحرارة (Pain Reliever / Fever Reducer). من شركة Julphar (جلفار). للاستعمال المستقيم وفق النشرة — للتوعية فقط.',
            'usage'                 => 'حسب النشرة أو وصفة الطبيب؛ يُستخدم الطريق المستقيم.',
            'dose'                  => 'حسب وزن الطفل والعمر والنشرة.',
            'frequency'             => 'حسب النشرة مع احترام الحد الأقصى اليومي للباراسيتامول.',
            'age'                   => 'غالباً للأطفال — راجع النشرة.',
            'storage'               => 'يُحفظ في مكان بارد إن طلبت النشرة ذلك؛ بعيداً عن متناول الأطفال.',
            'warnings'              => 'لا تجمع مع أدوية باراسيتامول أخرى. راجع الطبيب عند الحمى المستمرة.',
            'ingredients'           => 'Paracetamol 125 mg per suppository — راجع الملصق للأساس.',
            'contraindications'     => 'فرط الحساسية للباراسيتامول. موانع استعمال مستقيمية حسب النشرة.',
            'product_type'          => 'medicine',
            'prescription_required' => false,
            'hide_from_home'        => false,
            'categories'            => ['kids'],
            'cat'                   => 'kids',
            'category'              => 'kids',
            'subcategories'         => [126, 1],
            'active'                => true,
            'isCustom'              => true,
            'created_at'            => $now,
            'updated_at'            => $now,
        ],
    ];
}

function getDefaultSettings(): array {
    return [
        'phone'                       => '07711954040',
        'whatsapp'                    => '9647711954040',
        'address'                     => 'الديالى - خانقين | مقابل مجمع سوڤار',
        'openHour'                    => 15,
        'closeHour'                   => 24,
        'offDays'                     => [],
        'heroSlides'                  => getDefaultHeroSlides(),
        'heroSliderAutoplayMs'        => 2000,
        'categorySliderMode'          => 'manual',
        'categorySliderItems'         => getDefaultCategorySliderItems(),
        'homeSectionCategoryTitle'    => 'تسوّق حسب الفئة',
        'homeSectionCategoryKicker'   => 'تصفّح الأقسام',
        'homeSectionCategorySub'      => 'فئات مختارة بمنتجات جاهزة للطلب',
        'homeSpotlightVideos'         => ['', '', '', ''],
        'tagline'                     => 'صحتك أولويتنا — طلباتك عبر واتساب بسرعة وأمان',
        'deliveryTime'                => 'التوصيل خلال 24–48 ساعة حسب المنطقة والتوفر',
        'deliveryAreas'               => 'نخدم الديالى والمحافظات العراقية — للاستفسار عن منطقتك تواصل عبر واتساب',
        'googleMapsEmbedUrl'          => '',
    ];
}

function getDefaultHeroSlides(): array {
    return [
        ['id'=>'hero_default_1','image'=>'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1920&q=80','tag'=>'صيدلية موثوقة في الديالى','headline'=>'صحتك','headlineEm'=>'أولويتنا','headlineLine2'=>'أدوية أصلية وتوصيل سريع','subtitle'=>'تسوق بثقة — نصلك أينما كنت.','btnPrimaryText'=>'اطلب الآن','btnPrimaryHref'=>'#prod-sec','btnSecondaryText'=>'تصفح الأقسام','btnSecondaryHref'=>'categories.html','showWhatsAppBtn'=>true,'order'=>1,'active'=>true],
        ['id'=>'hero_default_2','image'=>'https://images.unsplash.com/photo-1631549916768-4119b2d5e946?auto=format&fit=crop&w=1920&q=80','tag'=>'عناية واستشارة','headline'=>'فيتامينات وعناية','headlineEm'=>'يومية','headlineLine2'=>'تصفّح منتجات مختارة بعناية','subtitle'=>'أدوية أصلية وتوصيل سريع في خانقين والمنطقة.','btnPrimaryText'=>'الأكثر طلباً','btnPrimaryHref'=>'#prod-sec','btnSecondaryText'=>'تصفح الأقسام','btnSecondaryHref'=>'categories.html','showWhatsAppBtn'=>true,'order'=>2,'active'=>true],
        ['id'=>'hero_default_3','image'=>'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1920&q=80','tag'=>'جودة معتمدة','headline'=>'رعاية صحية','headlineEm'=>'متكاملة','headlineLine2'=>'من صيدليتك الموثوقة','subtitle'=>'توصيل سريع، أسعار مناسبة، ومتابعة لطلبك.','btnPrimaryText'=>'تصفح الأقسام','btnPrimaryHref'=>'categories.html','btnSecondaryText'=>'سياسة الخصوصية','btnSecondaryHref'=>'privacy.html','showWhatsAppBtn'=>true,'order'=>3,'active'=>true],
    ];
}

function getDefaultCategorySliderItems(): array {
    return [
        ['id'=>'cslide_1','image'=>'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80','title'=>'مسكنات الألم والحرارة','subtitle'=>'ألم وحمى','icon'=>'💊','linkType'=>'subcategory','linkValue'=>'1','order'=>1,'active'=>true],
        ['id'=>'cslide_2','image'=>'https://images.unsplash.com/photo-1631549916768-4119b2d5e946?auto=format&fit=crop&w=800&q=80','title'=>'أدوية البرد والإنفلونزا','subtitle'=>'برد وزكام','icon'=>'🤒','linkType'=>'subcategory','linkValue'=>'2','order'=>2,'active'=>true],
        ['id'=>'cslide_3','image'=>'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80','title'=>'أدوية الجلدية','subtitle'=>'حكة وأكزيما','icon'=>'🧴','linkType'=>'subcategory','linkValue'=>'14','order'=>3,'active'=>true],
        ['id'=>'cslide_4','image'=>'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=800&q=80','title'=>'أدوية المعدة والحموضة','subtitle'=>'هضم وراحة','icon'=>'🤢','linkType'=>'subcategory','linkValue'=>'5','order'=>4,'active'=>true],
    ];
}

function getDefaultCategories(): array {
    return [
        ['id'=>1,'name'=>'الأدوية',          'slug'=>'medicine','icon'=>'💊','active'=>true,'order'=>1],
        ['id'=>2,'name'=>'التجميل',           'slug'=>'cosmetics','icon'=>'💄','active'=>true,'order'=>2],
        ['id'=>3,'name'=>'المستلزمات الطبية','slug'=>'medical', 'icon'=>'🩺','active'=>true,'order'=>3],
        ['id'=>4,'name'=>'الأطفال',           'slug'=>'kids',    'icon'=>'👶','active'=>true,'order'=>4],
        ['id'=>5,'name'=>'الفيتامينات',       'slug'=>'vitamins','icon'=>'🧬','active'=>true,'order'=>5],
        ['id'=>6,'name'=>'العناية بالشعر',    'slug'=>'haircare','icon'=>'💇','active'=>true,'order'=>6],
        ['id'=>7,'name'=>'العناية بالفم والأسنان','slug'=>'oralcare','icon'=>'🦷','active'=>true,'order'=>7],
    ];
}

/**
 * قائمة البذور للأقسام الفرعية — تُدمج في قاعدة البيانات عند التحميل إن وُجد القسم الرئيسي ولم يكن الاسم مسجّلاً.
 * الأدوية + تجميل + أطفال + مستلزمات طبية + فيتامينات + أقسام إضافية شائعة (عند وجودها في الأقسام الرئيسية).
 */
function getDefaultSubcategories(): array {
    return [
        // ——— الأدوية (medicine) ———
        ['id'=>1,  'name'=>'مسكنات الألم والحرارة',              'parent'=>'medicine','icon'=>'💊','active'=>true],
        ['id'=>2,  'name'=>'أدوية البرد والإنفلونزا',              'parent'=>'medicine','icon'=>'🤧','active'=>true],
        ['id'=>3,  'name'=>'السعال وطارد البلغم',                 'parent'=>'medicine','icon'=>'🫁','active'=>true],
        ['id'=>4,  'name'=>'حساسية (مضادات هيستامين)',            'parent'=>'medicine','icon'=>'🤧','active'=>true],
        ['id'=>5,  'name'=>'أدوية المعدة والحموضة',                'parent'=>'medicine','icon'=>'💊','active'=>true],
        ['id'=>6,  'name'=>'إسهال وجفاف (محاليل ORS)',             'parent'=>'medicine','icon'=>'💧','active'=>true],
        ['id'=>7,  'name'=>'إمساك وملينات',                       'parent'=>'medicine','icon'=>'🧻','active'=>true],
        ['id'=>8,  'name'=>'غثيان وقيء',                           'parent'=>'medicine','icon'=>'🤮','active'=>true],
        ['id'=>9,  'name'=>'التهاب الحلق',                        'parent'=>'medicine','icon'=>'🫁','active'=>true],
        ['id'=>10, 'name'=>'احتقان الأنف والجيوب الأنفية',         'parent'=>'medicine','icon'=>'👃','active'=>true],
        ['id'=>11, 'name'=>'قطرات العين',                         'parent'=>'medicine','icon'=>'👁️','active'=>true],
        ['id'=>12, 'name'=>'قطرات الأذن',                         'parent'=>'medicine','icon'=>'👂','active'=>true],
        ['id'=>13, 'name'=>'التهابات المسالك البولية',             'parent'=>'medicine','icon'=>'💊','active'=>true],
        ['id'=>14, 'name'=>'أدوية الجلدية (حكة، أكزيما)',          'parent'=>'medicine','icon'=>'🧴','active'=>true],
        ['id'=>15, 'name'=>'حب الشباب',                           'parent'=>'medicine','icon'=>'🫧','active'=>true],
        ['id'=>16, 'name'=>'مضادات فطريات',                       'parent'=>'medicine','icon'=>'🍄','active'=>true],
        // ——— التجميل (cosmetics) ———
        ['id'=>101, 'name'=>'العناية بالبشرة والمرطبات',           'parent'=>'cosmetics','icon'=>'🧴','active'=>true],
        ['id'=>102, 'name'=>'المكياج والألوان',                    'parent'=>'cosmetics','icon'=>'💄','active'=>true],
        ['id'=>103, 'name'=>'العناية بالشعر والتصفيف',             'parent'=>'cosmetics','icon'=>'💇','active'=>true],
        ['id'=>104, 'name'=>'العطور',                              'parent'=>'cosmetics','icon'=>'🌸','active'=>true],
        ['id'=>105, 'name'=>'إزالة الشعر والعناية',                'parent'=>'cosmetics','icon'=>'✨','active'=>true],
        ['id'=>106, 'name'=>'الأظافر والعناية',                    'parent'=>'cosmetics','icon'=>'💅','active'=>true],
        // ——— المستلزمات الطبية (medical) ———
        ['id'=>111, 'name'=>'أجهزة القياس (ضغط، سكر)',             'parent'=>'medical','icon'=>'🩺','active'=>true],
        ['id'=>112, 'name'=>'ضمادات وشاش ولاصقات طبية',            'parent'=>'medical','icon'=>'🩹','active'=>true],
        ['id'=>113, 'name'=>'مستلزمات الحقن والقطن',               'parent'=>'medical','icon'=>'💉','active'=>true],
        ['id'=>114, 'name'=>'الإسعافات الأولية',                   'parent'=>'medical','icon'=>'⛑️','active'=>true],
        ['id'=>115, 'name'=>'الدعامات والجبائر',                   'parent'=>'medical','icon'=>'🦴','active'=>true],
        ['id'=>116, 'name'=>'أقنعة واستنشاق',                      'parent'=>'medical','icon'=>'🫧','active'=>true],
        // ——— الأطفال (kids) ———
        ['id'=>121, 'name'=>'حفاضات ومستلزمات النظافة',            'parent'=>'kids','icon'=>'👶','active'=>true],
        ['id'=>122, 'name'=>'التغذية والحليب والمهروس',            'parent'=>'kids','icon'=>'🍼','active'=>true],
        ['id'=>123, 'name'=>'العناية ببشرة الطفل',                 'parent'=>'kids','icon'=>'🧴','active'=>true],
        ['id'=>124, 'name'=>'فيتامينات ومكملات أطفال',             'parent'=>'kids','icon'=>'🧬','active'=>true],
        ['id'=>125, 'name'=>'الرضاعة والهايات والزجاجات',          'parent'=>'kids','icon'=>'🍼','active'=>true],
        ['id'=>126, 'name'=>'أدوية شائعة للأطفال',                 'parent'=>'kids','icon'=>'💊','active'=>true],
        // ——— الفيتامينات (vitamins) ———
        ['id'=>131, 'name'=>'فيتامينات عامة',                      'parent'=>'vitamins','icon'=>'🧬','active'=>true],
        ['id'=>132, 'name'=>'الكالسيوم والعظام',                   'parent'=>'vitamins','icon'=>'🦴','active'=>true],
        ['id'=>133, 'name'=>'الطاقة والتعب',                       'parent'=>'vitamins','icon'=>'🔋','active'=>true],
        ['id'=>134, 'name'=>'المناعة وفيتامين ج',                  'parent'=>'vitamins','icon'=>'💪','active'=>true],
        ['id'=>135, 'name'=>'أوميغا وزيوت السمك',                  'parent'=>'vitamins','icon'=>'🐟','active'=>true],
        ['id'=>136, 'name'=>'الحديد والأنيميا',                   'parent'=>'vitamins','icon'=>'🩸','active'=>true],
        // ——— أقسام من قالب «إنشاء تلقائي» (عند وجود الـ slug) ———
        ['id'=>141, 'name'=>'شامبو وبلسم وعناية يومية',            'parent'=>'haircare','icon'=>'💇','active'=>true],
        ['id'=>142, 'name'=>'علاج التساقط وفروة الرأس',            'parent'=>'haircare','icon'=>'💆','active'=>true],
        ['id'=>143, 'name'=>'صبغات وتلوين',                        'parent'=>'haircare','icon'=>'🎨','active'=>true],
        ['id'=>151, 'name'=>'تنظيف وغسول البشرة',                  'parent'=>'skincare','icon'=>'🧼','active'=>true],
        ['id'=>152, 'name'=>'مرطبات وكريمات',                      'parent'=>'skincare','icon'=>'🧴','active'=>true],
        ['id'=>153, 'name'=>'واقي الشمس',                          'parent'=>'skincare','icon'=>'☀️','active'=>true],
        ['id'=>154, 'name'=>'مكافحة التجاعيد والعناية',            'parent'=>'skincare','icon'=>'✨','active'=>true],
        ['id'=>161, 'name'=>'معجون وفرشاة ومستلزمات الفم',         'parent'=>'oralcare','icon'=>'🦷','active'=>true],
        ['id'=>162, 'name'=>'غسول فم وللثة',                       'parent'=>'oralcare','icon'=>'🫧','active'=>true],
        ['id'=>171, 'name'=>'معقمات ومطهرات',                      'parent'=>'hygiene','icon'=>'🧴','active'=>true],
        ['id'=>172, 'name'=>'مناديل ومستلزمات نظافة',              'parent'=>'hygiene','icon'=>'🧻','active'=>true],
        ['id'=>181, 'name'=>'حقائب إسعاف وضمادات',                 'parent'=>'first_aid','icon'=>'🩹','active'=>true],
        ['id'=>182, 'name'=>'مستلزمات طوارئ منزلية',               'parent'=>'first_aid','icon'=>'⛑️','active'=>true],
    ];
}
